server:
  host: "localhost2"
  port: 8083
  url: "https"
database:
  jdbc-url: "postgres://user:pass@localhost:5432/db"
  username: "admin"
  password: "secret"
  retries: 2
  new:
    name: "Simple"
    main: "Main"
app:
  name: "MyApp"
  debug: false
  ports:
    - 8080
    - 8084
    - 5056